[package]
name = "vello-py"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
pollster = "0.4.0"
# https://github.com/PyO3/pyo3/commit/a5a65384a8e859aa4db7912fba30ed06bb7d4c8f
pyo3 = { git = "https://github.com/PyO3/pyo3", features = ["extension-module", "experimental-async"] }
vello_common = { git = "https://github.com/linebender/vello" }
vello_hybrid = { git = "https://github.com/linebender/vello" }
wgpu = { version = "27.0.1", default-features = false, features = ["wgsl", "std"] }
winit = { version = "0.30.12", default-features = false, features = ["rwh_06", "x11"] }

[dev-dependencies]
wgpu = { version = "27.0.1", default-features = false, features = ["wgsl", "std", "vulkan", "vulkan-portability"] }

[features]
# default = ["window"]
# window = ["winit"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2
