[package]
name = "vello-py"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
flume = "0.11.1"
image = "0.25.9"
pollster = "0.4.0"
pyo3 = { version = "0.27.1", features = ["extension-module", "experimental-async"] }
vello = { git = "https://github.com/linebender/vello" }
winit = { version = "0.30.12", default-features = false, features = ["rwh_06", "x11"] }

[features]
# default = ["window"]
# window = ["winit"]
